import Anthropic from "@anthropic-ai/sdk";

const SYSTEM_PROMPT = "You are the clinical AI assistant for ALGN Wellness, led by Dr. Alejandra, DC. Generate a personalized Hormone Assessment Report. This is a clinical education document, not a diagnosis. TONE: Warm, direct, clinical, empowering. Write as Dr. Alejandra speaking personally. OUTPUT use these exact headers no markdown: YOUR HORMONE PATTERN — 3-4 sentences naming her top symptom clusters and validating her experience. WHAT THIS MAY MEAN — 4-5 sentences on hormonal drivers, name hormones estrogen progesterone cortisol thyroid insulin, use may suggest can indicate is often associated with. YOUR BODY SYSTEM SCORES — list each with X/10 and one sentence: Hormones, Energy Systems, Mood and Cognition, Sleep, Metabolism, Gut Health, Pain and Inflammation. RECOMMENDED LAB MARKERS — 4 functional labs with descriptions available through Rupa Health. YOUR NEXT STEP — 2-3 sentences ending with: Your first step is a Hormone Clarity Session with Dr. Alejandra — a focused 60-minute consultation where we map your path forward together. A NOTE FROM DR. ALEJANDRA — 2-3 warm personal sentences signed: — Dr. Alejandra, DC | ALGN Wellness. IMPORTANT DISCLAIMER — This report is a clinical education document generated by ALGN Wellness AI and reviewed by Dr. Alejandra DC. It does not constitute a medical diagnosis medical advice or a doctor-patient relationship. NEVER diagnose. NEVER prescribe. ALWAYS use hedged clinical language.";

const ALLOWED_ORIGINS = [
  "http://localhost:3000",
  "http://localhost:5173",
  "https://algn-wellness.com",
  "https://www.algn-wellness.com"
];

export default async function handler(req, res) {
  const origin = req.headers.origin || "";
  const allowed = ALLOWED_ORIGINS.includes(origin) ? origin : ALLOWED_ORIGINS[0];
  const cors = {
    "Access-Control-Allow-Origin": allowed,
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Access-Control-Allow-Headers": "Content-Type"
  };
  if (req.method === "OPTIONS") { res.writeHead(204, cors); res.end(); return; }
  if (req.method !== "POST") { res.writeHead(405, cors); res.end(JSON.stringify({error:"Method not allowed"})); return; }
  if (!process.env.ANTHROPIC_API_KEY) { res.writeHead(500, cors); res.end(JSON.stringify({error:"Missing API key"})); return; }
  const { firstName, avatar, scores, openText } = req.body || {};
  if (!firstName || !avatar || !scores) { res.writeHead(400, cors); res.end(JSON.stringify({error:"Missing fields"})); return; }
  const AVATARS = {
    achiever: "The Achiever 35-42 PCOS hormone imbalance",
    transitional: "The Transitional 43-52 Perimenopause brain fog sleep changes",
    optimized: "The Optimized 30-38 Feels awful despite normal labs"
  };
  const scoreLines = Object.entries(scores).map(([k,v]) => k+": "+v+"/4").join(", ");
  const userMsg = "Generate a Hormone Assessment Report. NAME: "+firstName+" AVATAR: "+AVATARS[avatar]+" SCORES: "+scoreLines+" PATIENT WORDS: "+(openText||"Not provided")+" Generate the full report now.";
  try {
    const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });
    const message = await client.messages.create({
      model: "claude-sonnet-4-6",
      max_tokens: 1500,
      system: SYSTEM_PROMPT,
      messages: [{ role: "user", content: userMsg }]
    });
    const report = message.content?.map(b => b.text||"").join("") || "";
    res.writeHead(200, {...cors, "Content-Type":"application/json"});
    res.end(JSON.stringify({ report }));
  } catch(err) {
    console.error(err);
    res.writeHead(502, cors);
    res.end(JSON.stringify({error:"Failed to generate report. Please try again."}));
  }
}
